#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap		 20 

bspc config top_padding		100 
bspc config bottom_padding	100	 
bspc config left_padding	200 
bspc config right_padding	200 


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#Reduce Screen Tearing
compton -b --backend glx --paint-on-overlay --vsync opengl-swc

#Set Background Wallpaper
feh --bg-fill ~/.config/Themes/backgroundDefault.png
